### ISSUE TITLE
Develop project impact tracking and use it for planning

### ISSUE THREAD

**Issue by neilmb** [18F/usgs-groundwater#11]
We haven't developed as a team our project impact metrics. Let's do that and then we can use those as a reference to help plan out the time until the midpoint presentation and beyond.

- [x] Pull metrics from activity into a tracking spreadsheet
- [ ] Identify what baseline data we can collect to measure against metrics
- [ ] Create follow on tickets as needed

**Comment by neilmb** [comment]
Tracking spreadsheet is at https://docs.google.com/spreadsheets/d/1N8yjqG8IF10gUSuWsaYKrquPhLhkOGLwifZ4kRrDtMs/edit#gid=1999744232
