### ISSUE TITLE
Conduct first round of interviews

### ISSUE THREAD

**Issue by cmajel** [18F/usgs-groundwater#14]
**Background**
We've identified some key research goals for initial investigation:
* Document who is looking for groundwater data and their goals and pain points when accessing it.
* Identify how USGS currently approaches collecting and sharing groundwater data, what changes are planned, and the health of the network.

Based on these goals, we've developed research plans and conversation guides for 1:1 interviews

**We'll know we're done when**
- [x] Interviews are completed and we have notes/recordings to use for synthesis #12 

**Tasks**
- [x] Work with Candice and Daryll to identify research participants 
- [x] Review help desk emails for research participants
- [x] Schedule interviews
- [x] Conduct interviews
- [x] Ensure notes and recordings are coded and in a private folder

**Materials**
Research plans and protocols

- [For stakeholder interviews](https://docs.google.com/document/d/1FoqkJU77M_2WSNptve22e6oYYNdXHkfGmK-6-4PbAf0/edit#) (people within USGS who are affected by the data portal's work and management)
  - [For IoW developers](https://docs.google.com/document/d/1zkeAYHmG8-DzzMkutvt2qW89_1gpN9-2ItMJqSAQfQo/edit)
- For [data user interviews](https://docs.google.com/document/d/19LP5GoNEVqiEPQEjuWH0mtUxH3kpnpHTXIvQj3CvhkY/edit#heading=h.isx70ge51480) (USGS and non USGS, hydrologists, water scientists, modelers, and academics)

**Comment by cmajel** [comment]
This is in progress, and we're targeting to have our last interview 11/9

Here's a run down of the interviews scheduled:

Total: 14 interviews in round 1

Data users
* 9 interviews scheduled, including 2 modelers, 1 academic, 4 state/local groundwater specialists, 4 USGS groundwater specialists

Stakeholders
* 5 interviews scheduled, including 2 devs
