### ISSUE TITLE
Discuss technical feasibility

### ISSUE THREAD

**Issue by cmajel** [18F/usgs-groundwater#19]
**Background**
If we are going to recommend that NGWMN data should be made available in the WDFN system, then we need to understand how that data would flow from NGWMN into NWIS. Jim Kreft is the backend product owner and the NGWMN and WDFN backend dev teams know each other and could talk together with us to help us understand how to make that happen.

**Tasks**
- [x] Schedule discussion with Jim Kreft
  - Scheduled for 11/30
- [x] Schedule group discussion on dev integration
   - Scheduled for 11/29
- [ ] Develop guide for dev discussion
- [ ] Synthesize findings
