### ISSUE TITLE
Topic: Get better sense of NGWMN ecosystem

### ISSUE THREAD

**Issue by cmajel** [18F/usgs-groundwater#2]
**Background**
We're getting up to speed on how NGWMN operates, how it interacts with other USGS products, and who are the stakeholders in the network. This issue is to document some of the areas we want to dig into more with the WMA team; it may get broken down into more discrete issues. 

**We'll know we're done when...**
- [x] We've documented how data gets sent to NGWMN and who sends it
- [x] We've documented where NGWMN lives in the USGS product ecosystem
- [x] We've documented how NGWMN is currently maintained
- [x] We've mapped who's affected by NGWMN and USGS groundwater data

**Tasks**
- [x] Meet with Candice
- [x] Document what we learned in a shared team space

**Comment by cmajel** [comment]
Rough notes:

Tell us more about the data sources that feed into NGWMN.

- What's a non-USGS data provider?
- How can data providers send in data?

Where does NGWMN live in the USGS ecosystem? How does it interact with...

- Groundwater Watch
- “many of the Nation’s aquifers are not adequately described by the water-level data provided by Groundwater Watch. A more comprehensive monitoring program for the Nation’s aquifers is needed.”
- WDFN
- Water Quality Portal

How is NGWMN maintained currently?

- Who maintains it?
- What sort of feature requests come in? From who? How do they come in?
- Technical design documents
- Software development process? Stories/Epics/Roadmaps/Tickets/Staffing

Mapping who is affected by NGWMN decisions. 

- Who are the end-users of the site?
   - The public
   - Scientists?
   - Non-experts?
   - USGS using its own data?
- API consumers?
- Data provider’s experience
- System maintainers experience
- Other USGS teams?

**Comment by neilmb** [comment]
Funding: who funds these systems and at what level? What impact do different funding mechanisms have on decision-making?

**Comment by neilmb** [comment]
Congressional mandate: what does this mean exactly and who decides that?

**Comment by cmajel** [comment]
We may not get to  mapping stakeholders tomorrow, but this may be a kickoff activity #8 . We can talk more at Friday coworking about this.

**Comment by chopkins-usgs** [comment]
To provide data to the NGWMN Data Portal, providers have to both:

- Enter a list of acceptable sites in the Monitoring Location Registry
- Provide web services with data. The tip sheet for web services has been uploaded into our Google Drive or is available on the web.

**Comment by chopkins-usgs** [comment]
Guidance for providers to the NGWMN Data Portal can be found here: https://cida.usgs.gov/ngwmn/learnmore.jsp

**Comment by neilmb** [comment]
Mural of the ecosystem and the various products is here https://app.mural.co/t/gsa6/m/gsa6/1633545432112/190da40465b1dc41199f6149470e3f41868e2db3

Mural of the people affected from the kickoff meeting https://app.mural.co/t/gsa6/m/gsa6/1633698865030/61c396cbebba31747e7b5137bf34959a0af72775?sender=neilmartinsenburrell8204
