### ISSUE TITLE
Topic: research planning and prioritization

### ISSUE THREAD

**Issue by cmajel** [18F/usgs-groundwater#3]
**Background**
We've already identified a number of places where we have questions and could investigate more. This ticket is for documenting what we want to learn and questions we have so that we can focus our work and research.

**We'll know we're done when**
* We've identified which research questions we have and which we want to start with.

**Tasks**
- [x] Map out questions we want to answer with Candice
- [x] Prioritize with Candice
- [x] Create follow on research planning tickets as needed
- [ ] What else?

**Comment by cmajel** [comment]
@chopkins-usgs I wanted to share the research plans I have so far:
* [For stakeholder interviews](https://docs.google.com/document/d/1FoqkJU77M_2WSNptve22e6oYYNdXHkfGmK-6-4PbAf0/edit#)
* [ For data user interviews](https://docs.google.com/document/d/19LP5GoNEVqiEPQEjuWH0mtUxH3kpnpHTXIvQj3CvhkY/edit#heading=h.isx70ge51480)

The stakeholder interview guide is more fleshed out than the data user interviews, since we're starting those first. I could use feedback on the distribution of the participants under [Recruiting for data user interviews](https://docs.google.com/document/d/19LP5GoNEVqiEPQEjuWH0mtUxH3kpnpHTXIvQj3CvhkY/edit#heading=h.isx70ge51480).

**Comment by cmajel** [comment]
This was completed for the first round of interviews, so I am closing this. We'll revisit this topic in #16 

We have also been tracking additional [open questions in this doc](https://docs.google.com/document/d/19fTdMPoqKZlrxyc23fl_oauSXwnoz_t1J9yrN53XG4I/edit#).
