### ISSUE TITLE
Set up weekly ship

### ISSUE THREAD

**Issue by cmajel** [18F/usgs-groundwater#4]
**Background**
We want to keep the 18F and USGS teams interested in this project updated on what we've been working on. We generally send a weekly ship email to stakeholders that includes information like:
* What we did this week
* What's coming up
* Risk/blockers
* Budget recap

**Tasks**
- [x] Set up a weekly ship template
- [x] Talk with Candice/Emily about who should be included on the ship
- [x] Cowork on the first ship for Week 1

**Comment by neilmb** [comment]
Template document at https://docs.google.com/document/d/1Imv8l-mw3dfnsP3zY0DA_f8NrdaCcJRmi_U0OANW_5s
