### ISSUE TITLE
Create product vision and light roadmap with IIDD

### ISSUE THREAD

**Issue by neilmb** [18F/usgs-groundwater#7]
Can we make a blank scaffolding for product vision and product roadmap, maybe on the Github wiki, so that we can see them and start thinking about what needs to go into them.

Tasks
- [x] See past visioning activities for IIDD product
- [x] Determine who should be there
- [x] Schedule
- [ ] Plan activity and share with others for feedback
- [ ] Consider ways for others who can't attend to contribute
- [ ] Hold session
- [ ] Report out
