### ISSUE TITLE
Prepare for a kickoff meeting

### ISSUE THREAD

**Issue by neilmb** [18F/usgs-groundwater#8]
We will need a slide deck and then co-work on it with Candice and maybe get Emily's approval.

**Tasks**
- [x] Discuss kickoff goals with Candice; develop an outline
- [x] Create and cowork on deck
- [x] Share with Candice/Emily for feedback

**Comment by chopkins-usgs** [comment]
@neilmb  and @cmajel , it's looking like 1:00 pm MT/3:00 pm ET is open for most folks on 10/12. Does this time work? Is an hour the right amount of time?

**Comment by cmajel** [comment]
@chopkins-usgs 1pm Mt / 3pm ET on 10/12 works for us. And yes an hour sounds right to us.

**Comment by chopkins-usgs** [comment]
Invitations have been sent!

**Comment by cmajel** [comment]
This is done! Adding the [kickoff deck link](https://docs.google.com/presentation/d/1uMcqoBCpiurpgZP8G8z0Vscx-vnZX3IECtVcqGYoaqo/edit#slide=id.gf6d01f35b8_0_5) for posterity.
